name: cdk

on:
  push:
    branches:
        - master
  pull_request:

jobs:
  aws_cdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup dependencies
        run: npm ci

      - name: Setup lambda dependencies
        run: npm run lambda:ci

      - name: Build
        run: npm run build
        env:
          SLACK_INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          IFTTT_WEBHOOK_URL: ${{ secrets.IFTTT_WEBHOOK_URL }}
          MVTK_USER: ${{ secrets.MVTK_USER }}
          MVTK_PASSWORD: ${{ secrets.MVTK_PASSWORD }}

      - name: Unit tests
        if: contains(github.event_name, 'pull_request')
        run: cd lib/lambdas && npm test
          
      - name: CDK Diff Check
        if: contains(github.event_name, 'pull_request')
        run: npm run cdk diff
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACK_INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          IFTTT_WEBHOOK_URL: ${{ secrets.IFTTT_WEBHOOK_URL }}
          MVTK_USER: ${{ secrets.MVTK_USER }}
          MVTK_PASSWORD: ${{ secrets.MVTK_PASSWORD }}

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: npm run cdk:deploy:ci
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACK_INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          IFTTT_WEBHOOK_URL: ${{ secrets.IFTTT_WEBHOOK_URL }}
          MVTK_USER: ${{ secrets.MVTK_USER }}
          MVTK_PASSWORD: ${{ secrets.MVTK_PASSWORD }}
